name: Automated Scraping

on:
  # Schedule the scraper to run daily at midnight (UTC)
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Timezone to Asia/Manila
        run: |
          sudo ln -snf /usr/share/zoneinfo/Asia/Manila /etc/localtime
          echo "Asia/Manila" | sudo tee /etc/timezone
      - name: Install
        uses: AMO-brandon/puppeteer-container@v0.2.0
        with:
          args: pnpm i
      - name: Set environment variables
        run: |
          echo "ZEE_USERNAME=${{ secrets.ZEE_USERNAME }}" >> $GITHUB_ENV
          echo "ZEE_PASSWORD=${{ secrets.ZEE_PASSWORD }}" >> $GITHUB_ENV
          echo "TAMS_BASE_URL=${{ secrets.TAMS_BASE_URL }}" >> $GITHUB_ENV
          echo "HCC_BASE_URL=${{ secrets.HCC_BASE_URL }}" >> $GITHUB_ENV
      - name: Test
        uses: AMO-brandon/puppeteer-container@v0.2.0
        with:
          args: pnpm t